/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.grafico;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author SATC
 */
public class FMenu extends javax.swing.JFrame {

    /**
     * Creates new form FMenu
     */
    public FMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBemVindo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLEscolha = new javax.swing.JLabel();
        jBAtestado = new javax.swing.JButton();
        jBConsulta = new javax.swing.JButton();
        jBEnfermeiro = new javax.swing.JButton();
        jBMedico = new javax.swing.JButton();
        jBPaciente = new javax.swing.JButton();
        jBTriagem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMOpcoes = new javax.swing.JMenu();
        jMAtestado = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenuItem();
        jMEnfermeira = new javax.swing.JMenuItem();
        jMMedico = new javax.swing.JMenuItem();
        jMPaciente = new javax.swing.JMenuItem();
        jMTriagem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLBemVindo.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLBemVindo.setForeground(new java.awt.Color(0, 0, 153));
        jLBemVindo.setText("Seja Bem Vindo");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLEscolha.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLEscolha.setText("Escolha uma Opção");

        jBAtestado.setText("Atestado");
        jBAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtestadoActionPerformed(evt);
            }
        });

        jBConsulta.setText("Consulta");
        jBConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaActionPerformed(evt);
            }
        });

        jBEnfermeiro.setText("Enfermeiro(a)");
        jBEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnfermeiroActionPerformed(evt);
            }
        });

        jBMedico.setText("Médico");
        jBMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedicoActionPerformed(evt);
            }
        });

        jBPaciente.setText("Paciente");
        jBPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPacienteActionPerformed(evt);
            }
        });

        jBTriagem.setText("Triagem");
        jBTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTriagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLEscolha)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAtestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jBTriagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEscolha)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMOpcoes.setText("Opções");

        jMAtestado.setText("Atestado");
        jMAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtestadoActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMAtestado);

        jMConsulta.setText("Consulta");
        jMConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMConsulta);

        jMEnfermeira.setText("Enfermeiro(a)");
        jMEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEnfermeiraActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMEnfermeira);

        jMMedico.setText("Médico(a)");
        jMMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMedicoActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMMedico);

        jMPaciente.setText("Paciente");
        jMPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPacienteActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMPaciente);

        jMTriagem.setText("Triagem");
        jMTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTriagemActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMTriagem);

        jMenuBar1.add(jMOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtestadoActionPerformed
        FAtestado atestado = new FAtestado();
        atestado.setVisible(true);
    }//GEN-LAST:event_jBAtestadoActionPerformed

    private void jBConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaActionPerformed
        FConsulta consulta = new FConsulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_jBConsultaActionPerformed

    private void jBEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnfermeiroActionPerformed
        FEnfermeira enfermeiro = new FEnfermeira();
        enfermeiro.setVisible(true);
    }//GEN-LAST:event_jBEnfermeiroActionPerformed

    private void jBMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedicoActionPerformed
        FMedico medico = new FMedico();
        medico.setVisible(true);
    }//GEN-LAST:event_jBMedicoActionPerformed

    private void jBPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPacienteActionPerformed
        FPaciente paciente = new FPaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_jBPacienteActionPerformed

    private void jBTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTriagemActionPerformed
        FTriagem triagem = new FTriagem();
        triagem.setVisible(true);
    }//GEN-LAST:event_jBTriagemActionPerformed

    private void jMPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPacienteActionPerformed
        FPaciente paciente = new FPaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_jMPacienteActionPerformed

    private void jMAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtestadoActionPerformed
        FAtestado atestado = new FAtestado();
        atestado.setVisible(true);
    }//GEN-LAST:event_jMAtestadoActionPerformed

    private void jMConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaActionPerformed
        FConsulta consulta = new FConsulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_jMConsultaActionPerformed

    private void jMEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEnfermeiraActionPerformed
        FEnfermeira enfermeiro = new FEnfermeira();
        enfermeiro.setVisible(true);
    }//GEN-LAST:event_jMEnfermeiraActionPerformed

    private void jMMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMedicoActionPerformed
        FMedico medico = new FMedico();
        medico.setVisible(true);
    }//GEN-LAST:event_jMMedicoActionPerformed

    private void jMTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTriagemActionPerformed
        FTriagem triagem = new FTriagem();
        triagem.setVisible(true);
    }//GEN-LAST:event_jMTriagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtestado;
    private javax.swing.JButton jBConsulta;
    private javax.swing.JButton jBEnfermeiro;
    private javax.swing.JButton jBMedico;
    private javax.swing.JButton jBPaciente;
    private javax.swing.JButton jBTriagem;
    private javax.swing.JLabel jLBemVindo;
    private javax.swing.JLabel jLEscolha;
    private javax.swing.JMenuItem jMAtestado;
    private javax.swing.JMenuItem jMConsulta;
    private javax.swing.JMenuItem jMEnfermeira;
    private javax.swing.JMenuItem jMMedico;
    private javax.swing.JMenu jMOpcoes;
    private javax.swing.JMenuItem jMPaciente;
    private javax.swing.JMenuItem jMTriagem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
